---
# This workflow integrates ShiftLeft with GitHub
# Visit https://docs.shiftleft.io for help
name: Qwiet AI

on:
  push:
    branches:
     - master
     - main
  pull_request:
  workflow_dispatch:

jobs:
  preZero:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Qwiet cli
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - uses: AppThreat/cpggen-action@main
      with:
        out_dir: "/github/workspace/cpg_out"
        lang: jar
      env:
        SL_CPG_OPTS: "-J-Xms2g -J-Xmx7g"
        SHIFTLEFT_JAVA_OPTS: "-Xms2g -Xmx7g"
        AT_DEBUG_MODE: "debug"
    - name: Analyze
      run: |
        #####
        # Run Qwiet analysis
        for i in `ls ${GITHUB_WORKSPACE}/cpg_out/*.manifest.json`; do
          cpg=$(jq -r ".cpg" $i)
          sbom=$(jq -r ".sbom" $i)
          language=$(jq -r ".language" $i)
          ${GITHUB_WORKSPACE}/sl analyze --policy io.shiftleft/defaultWithDictAndBestPractices --tag app.group=$(basename $(pwd)) --app $(basename $(pwd))-$language --$language --cpgupload --bomupload $sbom $cpg
        done
        #####
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SL_CPG_OPTS: "-J-Xms2g -J-Xmx7g"
        SHIFTLEFT_JAVA_OPTS: "-Xms2g -Xmx7g"
    - name: Upload cpg
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cpg
        path: cpg_out
